import {BrandingModal} from "@/components/admin/components/modals/branding-modal";
import {ContactModal} from "@/components/admin/components/modals/contact-modal";
import {SocialModal} from "@/components/admin/components/modals/social-modal";
import {ThemeModal} from "@/components/admin/components/modals/theme-modal";
import Footer from "@/components/layout/footer";
import Header from "@/components/layout/header";
import ReactQueryProvider from "@/providers/reactquery-provider";
import ReduxProvider from "@/providers/redux-provider";
import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<ReduxProvider>
					<ReactQueryProvider>
						<Header />
						{children}
						<BrandingModal />
						<ContactModal />
						<SocialModal />
						<ThemeModal />
						<Footer />
					</ReactQueryProvider>
				</ReduxProvider>
			</body>
		</html>
	);
}
